#! /usr/bin/env php

<?php 

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

$app = new Application();

$app->register('sayHi')
     ->addArgument('name')
     ->setCode(function(InputInterface $input, OutputInterface $output) {

         $output->writeln('Hello World');

     });
     
$app->run();