#! /usr/bin/env php

<?php 

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Citrus\SayHiCommand;


$app = new Application('Letus','1.0');

$app->add(new SayHiCommand);
     
$app->run();